apiVersion: v1
kind: Service
metadata:
  name: ephex
  labels:
    app: ephex
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: "9230"
    protocol: TCP
  selector:
    app: ephex
